// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgpYAouQwOQqN0YSPeRmFz3hCRefSg8co',
    appId: '1:175500440586:android:ce8d8a2753569a20ff5bf3',
    messagingSenderId: '175500440586',
    projectId: 'jomiobusineogbook',
    storageBucket: 'jomiobusineogbook.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8lancx_kZVG3tIrDe5mu8yBFcHoxDkDA',
    appId: '1:175500440586:ios:daf9b724265f370fff5bf3',
    messagingSenderId: '175500440586',
    projectId: 'jomiobusineogbook',
    storageBucket: 'jomiobusineogbook.firebasestorage.app',
    iosBundleId: 'com.example.jomioBusinessLogbook',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOQ_SyCzPoQRyjsx20HEkmIPJYRdG-H9o',
    appId: '1:175500440586:web:03ce44a291cdde54ff5bf3',
    messagingSenderId: '175500440586',
    projectId: 'jomiobusineogbook',
    authDomain: 'jomiobusineogbook.firebaseapp.com',
    storageBucket: 'jomiobusineogbook.firebasestorage.app',
    measurementId: 'G-4BNKL4CHQW',
  );
}
